test-rust:
  image: termoshtt/rust
  cache:
    untracked: true
  script:
    - cd rust/
    - cargo test

run-rust:
  image: termoshtt/rust
  cache:
    untracked: true
  script:
    - cd rust/
    - sqlite3 test.db < src/sqlite/init.sql
    - cargo run --release --bin l63_enkf2 sample_setting.json test.db
