test-rust:
  image: termoshtt/rust
  cache:
    paths:
      - rust/target/
  script:
    - cd rust/
    - cargo test -vv

test-python:
  image: termoshtt/scipy:3.5
  script:
    - cd python
    - pip install -r requirements.txt
    - nosetests --with-doctest -v
