test-rust:
  image: termoshtt/rust
  cache:
    untracked: true
  script:
    - cd rust
    - cargo test

run-rust:
  image: termoshtt/rust
  cache:
    untracked: true
  script:
    - cd rust/
    - cargo run --release --bin l63_truth sample_setting.json test.db
    - cargo run --release --bin l63_observation sample_setting.json test.db
    - cargo run --release --bin l63_enkf2 sample_setting.json test.db
