test-rust:
  image: termoshtt/rust
  cache:
    untracked: true
  script:
    - cd rust
    - cargo test

run-rust:
  image: termoshtt/rust
  cache:
    untracked: true
  script:
    - cd rust/
    - ./run.zsh sample_setting.json enkf
    - ./run.zsh sample_setting.json etkf
    - ./run.zsh sample_setting.json mpf
