[package]
name = "aics-da"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
rmp = "*"
rustc-serialize = "*"
rmp-serialize = "*"
rand = "*"
ndarray-rand = "*"

[dependencies.ndarray]
version = "*"
default-features = false
features = ["blas", "rustc-serialize"]

[dependencies.ndarray-odeint]
git = "http://github.com/termoshtt/ndarray-odeint.git"

[dependencies.ndarray-linalg]
git = "http://github.com/termoshtt/ndarray-linalg.git"
