[package]
name = "aics-da"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
rmp = "*"
serde = "*"
serde_derive = "*"
rustc-serialize = "*"
rmp-serialize = "*"
rand = "*"
ndarray = { version = "0.9", features = ["blas", "rustc-serialize"] }
ndarray-rand = "*"
ndarray-linalg = "0.5"
ndarray-odeint = "0.5"
itertools = "*"
docopt = "*"
pbr = "*"
float-cmp = "*"
num-traits = "*"
derive-new = "*"
log = "*"
env_logger = "*"
dotenv = "*"
