#!/usr/bin/env python
#coding=utf-8

import msgpack
import argparse


def main():
    p = argparse.ArgumentParser()
    p.add_argument("filename", help="filename of msgpack to be shown")
    args = p.parse_args()
    with open(args.filename, "rb") as f:
        data = msgpack.load(f)
    print(data)

if __name__ == '__main__':
    main()
