[package]
name = "aics-da"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
rmp = "*"
rustc-serialize = "*"
rmp-serialize = "*"
rand = "*"
ndarray-rand = "*"
num-traits = "*"
ndarray-linalg = "*"
ndarray-odeint = "*"
itertools = "*"
docopt = "*"
pbr = "*"
rusqlite = "*"
time = "*"
float-cmp = "*"
uuid = { version = "0.2", features = ["v4"] }

[dependencies.ndarray]
version = "*"
default-features = false
features = ["blas", "rustc-serialize"]

[dev-dependencies]
ndarray-numtest = "0.1.2"
